### ISSUE TITLE
How to use fastapi-events dispatch as task with sqs-polling

### ISSUE THREAD

**Issue by grizzly-monkey** [nonchan7720/sqs-polling#28]
```Python
def poll(event_name: EventName, service_id: int, **kwargs):
    @polling(**kwargs)
    def s3_upload_task(
        self: Polling,
        message_body: str,
        message_attribute: dict[str, Any] | None,
        message_group_id: str | None,
        message_duplication_id: str | None,
    ):
        data: dict[str, Any] = json.loads(message_body)
        records = data["Records"]
        pprint(message_body)
        pprint(data)

        for record in records:
            s3_record = record["s3"]
            s3_upload_object = SQSS3Object(**s3_record)

            asyncio.create_task(dispatch_task(event_name, s3_upload_object, service_id))
```

however i get below errror

```
ERROR:sqs_polling.polling:no running event loop
Traceback (most recent call last):
  File "/opt/lk/eda-services/verifire_service/.venv/lib/python3.11/site-packages/sqs_polling/polling.py", line 215, in _execute
    p.handler(
  File "/opt/lk/eda-services/verifire_service/.venv/lib/python3.11/site-packages/shared/aws/sqs.py", line 52, in s3_upload_task
    try_with_me(event_name, s3_upload_object, service_id)
  File "/opt/lk/eda-services/verifire_service/.venv/lib/python3.11/site-packages/shared/aws/sqs.py", line 28, in try_with_me
    asyncio.create_task(dispatch_task(event_name, s3_upload_object, service_id))
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 371, in create_task
    loop = events.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop
Stack (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/lk/eda-services/verifire_service/.venv/lib/python3.11/site-packages/sqs_polling/polling.py", line 232, in _execute
    logger.error(e, exc_info=True, stack_info=True)
```

refer - 4) Dispatching events outside of a request of https://pypi.org/project/fastapi-events/

**Comment by nonchan7720** [comment]
@grizzly-monkey 
Thank you for creating the Issue.
In this case, the event loop must be started using the main function as implemented in the sample.

This library only supports either generating and executing an event loop in the main function, or using an event loop during execution,
This library only supports either creating and executing an event loop in the main function, or using an event loop during execution.
So, in the case of the code in the issue
You need to start the event loop at the entry point.
